include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
  exclude:
    - build/**
    - packages/noura_api_client/**
    - android/**
    - ios/**
    - web/**

linter:
  rules:
    - always_declare_return_types
    - avoid_print
    - prefer_const_constructors
    - prefer_final_locals
    - require_trailing_commas
    - sort_child_properties_last
    - unawaited_futures
